on:
  push:
    branches:
      - main
  pull_request:

name: Build & test

jobs:
  build_and_test:
    name:  push/pull build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Install node-JS 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.68.0'
      - name: Install Wasm-Pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.11.0'

      - name: building
        run: |
          npm ci
          npm run build
          npm run package
      
      - name: testing
        run: cargo test
