on:
  push:
    branches:
      - main
  pull_request:

name: Build & test

jobs:
  build_and_test:
    name:  Push/Pull build_and_test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Install node-JS 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.68'
      - name: Install Wasm-Pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.11.0'

      - name: Restore cached Build
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-${{ github.sha }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Building
        run: |
          npm ci
          npm run build
          npm run package
          cargo build --all-targets
          cargo build --release

      - name: Testing
        run: cargo test
        timeout-minutes: 1 

      - name: Save Build
        id: cache-build
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Artifact vsix file 
        uses: actions/upload-artifact@v3
        with:
          name: .vsix-file
          path: packages/p4-analyzer-vscode/p4-analyzer-vscode-*.vsix
          if-no-files-found: error
